#wiki entry: https://github.com/Daklyrus/docker-compose-files/wiki/Wiki#piwigo

version: "2.1"

services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - CONFIGDIR:/config
      - GALLERYDIR:/gallery
    ports:
      - CUSTOMPORT:80
    restart: unless-stopped
