# wiki entry: https://github.com/Daklyrus/docker-compose-files/wiki/Wiki/_edit#dokuwiki

version: "2.1"
services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - CONFIGDIR:/config
    ports:
      - CUSTOMPORT:80
    restart: unless-stopped
