version: "2.1"
services:
  papermerge:
    image: lscr.io/linuxserver/papermerge:latest
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - CONFIGDIR:/config
      - DATADIR:/data
    ports:
      - CUSTOMPORT:8000
    restart: unless-stopped
